### ISSUE TITLE
Google cloud open dialog does not show any datasets

### ISSUE THREAD

**Issue by axtimwalde** [saalfeldlab/bigcat#105]
The dialog to chose project and bucket comes up, but the choice list for datasets remains empty, no error message or any other information.

**Comment by axtimwalde** [comment]
Possible reasons: Listing takes too long, possibly iterating through all n5 subdirectories to generate the list?  The bucket is not small, Lauritzen volume with many datasets.

**Comment by axtimwalde** [comment]
The issue topic is not correct.  The choice list is getting populated correctly, but it takes several minutes for this to happen without indication that anything will happen.  This should be faster.  Probably an issue for n5-google-cloud listing @igorpisarev .

**Comment by igorpisarev** [comment]
It takes ~7s on my bucket with 21 dataset in total. Not fast, but it's about the same speed as you would get in the web interface, definitely not as bad as a few minutes.

I checked the n5-google-cloud code, and there was a bit of redundancy introduced with the recent changes (checking for subgroups instead of requiring `attributes.json` to be present for each group). I added an overridden implementation of `datasetExists()` that avoids an additional `exists()` call which lists subgroups. It improved the listing runtime from ~7s to ~5.5s. This optimization is included in the new release 2.3.0 of n5-google-cloud.

Another way to speed this up may be to list groups/datasets in a multithreaded fashion.

**Comment by hanslovsky** [comment]
@axtimwalde [dataset discovery](https://github.com/hanslovsky/bigcat/blob/multiscale-painting/src/main/java/org/janelia/saalfeldlab/paintera/ui/opendialog/N5Helpers.java#L149) iterates over all sub-groups and adds data sets as appropriate. It stops whenever a dataset is reached, i.e. it does not list the contents of a dataset, except when the n5 root itself is a data set (is that legal wrt the n5 spec?). Following your description of the data, I do not think that is the case for you but I will add a check for the initial directory anyway.

Another candidate is the [check for multiscale dataset](https://github.com/hanslovsky/bigcat/blob/multiscale-painting/src/main/java/org/janelia/saalfeldlab/paintera/ui/opendialog/N5Helpers.java#L178): For every sub-group,check for `s[0-9]+` naming pattern and if it is a dataset. If every data set has 10 scale levels, that increases the required time by 10. The solution for that is simple: We can put a `"multiScale:true" parameter in the `attributes.json` of a multi-scale group.

**Comment by hanslovsky** [comment]
Continuied in saalfeldlab/paintera#13
