### ISSUE TITLE
Get rid of BigDataViewer dependency

### ISSUE THREAD

**Issue by hanslovsky** [saalfeldlab/bigcat#17]
Historically, bigcat used bdv for viewing data. Thus, source management as grown around that and goes through hoops to accomodate. We should get rid of bdv dependencies entirely (especially `ViewerState` and `SourceState`) for better source and data management.

**Comment by tpietzsch** [comment]
While I understand the need for fast evolution independent of bdv-core, it would be much appreciated it if you contribute the better source and data management solution back to bdv (once you have it)...

**Comment by axtimwalde** [comment]
@hanslovsky @tpietzsch I also think that this issue is premature, badly phrased, and not actually in the interest of shared library development.  It is not our goal to remove all dependencies from everything just for the sake of it.  The *actual* issue is that we do not have a better source nor data management solution right now.  In the process of making BDV and imglib-ui work with JavaFX, Philipp had to replicate existing code with minor modifications which is not cool.  You can see these modifications in the branches https://github.com/hanslovsky/bigdataviewer-core/tree/bigcat-javafx and https://github.com/hanslovsky/imglib2-ui/tree/javafx and you will easily see that this is not nice.  Not only is code duplicated all over the board but both repositories got a JavaFX dependency added which is NOT cool.  On the other hand, bigdataviewer-core pulls in AWT dependencies and so would limit the port of a JavaFX based application to e.g. Android.  So our *true* plan is this: Roll back the modifications in bdv-core and imglib-ui.  Do experiments and modifications in BigCAT.  When we find good and generic solutions, contribute back.  This contribution back will probably mean that we would need an AWT free bdv-core and imglib2-ui and that would be a pretty significant change and so we decided to not start with the big change but do it when things are more clear.  I hope that explanation helps and I would like to close this issue.

**Comment by tpietzsch** [comment]
Sounds very reasonable. Maybe the AWT free code can all go into imglib2-ui, and then only Swing dialogs and SpimData glue would remain in bdv-core. Let's see. I agree it's better to wait until things are clear. I just wanted to point out that it would be great if bdv could benefit from bigcat developments eventually.

**Comment by hanslovsky** [comment]
I am sorry for my lack of clarity and confusion due to my short commit message @tpietzsch 
@axtimwalde made a much better comment on what our plans are and what we would like to see. Dresden will be a great time for us to experiment and try to extract common interfaces from both our use cases and experiences with awt and javafx, respectively. I am definitely looking forward to build on a common core.
